name: tests

on:
  pull_request:
    types: [opened, updated, synchronize, ready_for_review, review_requested]
    branches:
      - master
    paths:
      - "**"
  push:
    branches:
      - master

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: printing rust version
      run: rustc --version
    - name: printing cargo version
      run: cargo --version
    - name: running the unit tests
      run: cargo test
